[tool.poetry]
name = "python-class"
version = "0.1.0"
description = ""
authors = ["Alissa Huskey <alissa.huskey@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.24.0"
ipython = "^7.19.0"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]
xdoctest = "^0.15.0"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
