[tool.poetry]
name = "python-class"
version = "0.1.1"
description = ""
authors = ["Alissa Huskey <alissa.huskey@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
colorful = "^0.5.4"
tabulate = "^0.8.7"
click = "^7.1.2"
colorama = "^0.4.4"
more_itertools = "^8.6.0"
blessed = "^1.17.12"

[tool.poetry.dev-dependencies]
xdoctest = "^0.15.0"
black = "^20.8b1"
jupyter = "^1.0.0"
ipython = "^7.19.0"

# ---------------------------------------------------------------------
# docs
# ---------------------------------------------------------------------

ghp = { file = "vendor/gh-pages-cli/dist/ghp-0.1.2-py3-none-any.whl", optional = true }
# jupyter-book = { git = "https://github.com/executablebooks/jupyter-book.git" }
jupyter-book = { file = "vendor/jupyter-book/dist/jupyter_book-0.8.3-py3-none-any.whl", optional = true }
docutils = { version = "^0.16", optional = true }
sphinx = { version = "^3.3.1", optional = true }

# required for jupyter-book as of 0.8.3
# https://github.com/executablebooks/jupyter-book/issues/1137
sphinxcontrib-bibtex = { version = "<2.0.0", optional = true }

# required for jupyter-book as of around 0.8.3
zipp = { version = "^3.4.0", optional = true }
pytest = "^6.2.1"

[tool.poetry.extras]
docs = [
  "ghp",
  "jupyter-book",
  "docutils",
  "sphinx",
  "sphinxcontrib-bibtex",
  "zipp",
]

[build-system]
# requires = ["poetry>=0.12"]
# build-backend = "poetry.masonry.api"
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
