[tool.poetry]
name = "python-class"
version = "0.1.0"
description = ""
authors = ["Alissa Huskey <alissa.huskey@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
ipython = "^7.19.0"
colorful = "^0.5.4"
tabulate = "^0.8.7"
click = "^7.1.2"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
xdoctest = "^0.15.0"
black = "^20.8b1"
docutils = "^0.16"
jupyter-book = "^0.8.3"
jupyter = "^1.0.0"
sphinx = "^3.3.1"
ghp-import = "^1.0.0"
ipython = "^7.19.0"
zipp = "^3.4.0"  # dependency of jupyter-book

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
