#!/usr/bin/env zsh

main() {
  local version="$1" cast prog
  local -a cmd

  DISABLE_RPROMPT=true ; export DISABLE_RPROMPT

  cast="docs/exercises/assets/adventure-${version}.cast"
  prog="pythonclass/adventure/adventure-${version}.py"

  if [[ $# -gt 1 ]]; then
    cmd=( "${@:2}" )
  else
    cmd=( python "$prog" )
  fi

  poetry run asciinema rec --quiet --idle-time-limit 1 \
    --overwrite "${cast}" \
    --env SHELL,TERM,DISABLE_RPROMPT \
    --command "${cmd[*]}"

  hr
  echo "Done."
}

main ${1:+"$@"}
