#!/usr/bin/env zsh
#
# cast - record a screencast of the adventure game
#
# usage: cast VERSION [COMMAND...]
#

usage() {
  cat <<EOF

  cast - record a screencast of the adventure game

   usage:

     cast VERSION [COMMAND...]
     cast -h|--help

EOF
}

help() {
  usage
  cat <<EOF
  Arguments:

     VERSION        Version of adventure game to record
     COMMAND        Command to run instead of adventure game

EOF
}

main() {
  local version="$1" cast prog mode
  local -a cmd

  if [[ $# -eq 0 ]]; then
    usage
    exit 1
  fi

  [[ "-h" =~ "${*}" ]] && mode=help
  [[ "--help" =~ "${*}" ]] && mode=help

  if [[ "${mode}" == "help" ]]; then
    help
    exit
  fi

  DISABLE_RPROMPT=true ; export DISABLE_RPROMPT

  cast="docs/exercises/adventure/assets/adventure-${version}.cast"
  prog="pythonclass/adventure/adventure-${version}.py"

  if [[ $# -gt 1 ]]; then
    cmd=( "${@:2}" )
  else
    cmd=( python "$prog" )
  fi

  poetry run asciinema rec --quiet --idle-time-limit 1 \
    --overwrite "${cast}" \
    --env SHELL,TERM,DISABLE_RPROMPT \
    --command "${cmd[*]}"

  printf '\033[92m'
  hr
  printf '\033[0m'
  echo "Done."
}

main ${1:+"$@"}
