#!/usr/bin/env zsh
#
# difflast -- find the last version of adventure.py or test_game.py
#             and start a vimdiff between the two
#
#
# usage:
#
# difflast [adventure|test]
#

main() {
  local file="${1:-adventure}" current last

  [[ "$file" == "test" ]] && file="test_game"

  current="$(readlink -f "${file}.py")"
  for f in "pythonclass/adventure/${file}-"*(n); do
    [[ "${f##*/}" =~ "${current##*/}" ]] && break
    last="$f"
  done

  if [[ ! -f "${last}" ]]; then
    echo "last file not found"
    exit 1
  fi

  vimdiff "${last}" "${file}.py"
}

main ${1:="$@"}
