#!/usr/bin/env zsh
#
# difffin  -- find the final version of the current point version
#             and start a vimdiff between the two
#
#
# usage:
#
# difffin [adventure|test]
#

main() {
  local file="${1:-adventure}" current version final

  [[ "$file" == "test" ]] && file="test_game"

  current="$(readlink -f "${file}.py")"

  version="${current##*-}"     # x.x.py
  version="${version%.py}"     # x.x
  final="${version%.*}"        # x

  vimdiff "pythonclass/adventure/${file}-${final}.py" "${file}.py"
}

main ${1:="$@"}
