# jupyter-book settings
# Learn more at https://jupyterbook.org/customize/config.html

title                       : Python Class
author                      : Alissa Huskey <alissa.huskey@gmail.com>

execute:
  execute_notebooks         : force

# NOTE: Also in _ext/myroles.py
repository:
  url                       : https://github.com/alissa-huskey/python-class
  branch                    : master
  path_to_book              : docs

html:
  use_repository_button     : true
  extra_navbar              : ""
  baseurl                   : file:///Users/alissahuskey/Dropbox/projects/python-class/

parse:
  myst_extended_syntax      : true

launch_buttons:
  notebook_interface        : jupyterlab
  binderhub_url             : https://mybinder.org
  thebe                     : true

exclude_patterns            : [ todo.md, misky/*, reference/string-formatting.md, _ext/* ]

sphinx:
  local_extensions:
    myroles: _ext
  language: en
