# jupyter-book settings
# https://jupyterbook.org/customize/config.html

title                       : Python Class
author                      : ""  # footer (default "By The Jupyter Book community")

# NOTE: Also in _ext/myroles.py
repository:
  url                       : &repo https://github.com/alissa-huskey/python-class
  branch                    : &branch master
  path_to_book              : &path docs

exclude_patterns            :
                              - todo.md
                              - player.md
                              - misky/*
                              - _ext/*
                              - templates/*
                              - reference/string-formatting.md
                              - lessons/data/comprehensions.md
                              - lessons/mug-brownie.md
                              - lessons/keywords.md
                              - lessons/12-days-of-xmas-lyrics.md
                              - lessons/data-types/dunder-methods.md
                              - lessons/data-types/types.md
                              - exercises/richter.md
                              - practices/testing/given-when-then.md
                              - practices/testing/best-practices.md
                              - exercises/adventure/tpl.md

execute:
  execute_notebooks         : force

use_buttons: &use_buttons
  use_repository_button     : true
  use_edit_page_button      : true   # suggested edits

html:
  <<: *use_buttons
  baseurl                   : https://alissa-huskey.github.io/python-class/

parse: &parse
  # https://myst-parser.readthedocs.io/en/latest/configuration.html
  myst_heading_anchors      : 5
  myst_enable_extensions    : &myst_enable_extensions
                              - substitution
                              - colon_fence
                              - deflist
                                # - tasklist  # pending myst-parser v 0.14.0+
  myst_substitutions        :
    clear                   : '<div class="clearfix"></div>'
    leftcol                 : '<div class="row"><div class="col left-col">'
    rightcol                : '</div><div class="col">'
    newrow                  : '</div></div><div class="row"><div class="col right-col">'
    endcols                 : '</div></div>'
    br                      : '<div class="br"></div>'
    sourcebadge             : '{{bdg-link-success}}`source code <{0}>`'
    left                    : '{{ leftcol | replace("col", "col-5") }}'
    right                   : '{{ rightcol | replace("col", "col-7") }}'

    # teal badge linking to my github with configurable name
    # note: double curley braces make one literal brace (for .format())
    # usage: {{{{ code.format("filename.py", "text" }}}}
    code: |
      {{bdg-link-info-line}}`{0} <https://github.com/alissa-huskey/python-class/blob/master/pythonclass/{1}>`

    # for adventure game
    # --------------------------------------------------------------

    # green "source code" badge linking to my github
    # usage: {{ source | format("filename.py") }}
    source: |
      ```{div} float-right source-code
        {bdg-link-info-line}`source code <https://github.com/alissa-huskey/python-class/blob/master/pythonclass/adventure/%s>`

      {{ clear }}
      ```
    # two green badges, one for adventure-VERSION.py and one for test_game-VERSION.py
    # usage: {{ sources.format("VERSION") }}
    # note: double curley braces make one literal brace (for .format())
    sources: |
      ```{{div}} float-right source-code source-code-{0}
      {{{{ code.format("adventure.py", "adventure/adventure-{0}.py") }}}} {{{{ code.format("test_game.py", "adventure/test_game-{0}.py") }}}}

      {{{{ clear }}}}
      ```


launch_buttons: &launch_buttons
  notebook_interface        : jupyterlab
  binderhub_url             : https://mybinder.org
  thebe                     : true

sphinx:
  # https://www.sphinx-doc.org/en/master/usage/configuration.html
  language                  : en
  extra_extensions          :
                              - sphinx_thebe
                              - sphinx.ext.extlinks
                              - sphinx_exercise
                              - code_highlighter
                              - sphinxcontrib.kroki
                              - sphinx_tabs.tabs
                              - sphinx_jinja
  local_extensions          :
    lexicon                 : _ext
    fieldlist               : _ext
    screencast              : _ext
    screenshot              : _ext
    bullseye                : _ext
  config                    :
    <<                      : *parse
    myst_enable_extensions  : *myst_enable_extensions
    extlinks                :
      github                : [ http://github.com/alissa-huskey/python-class/blob/master/%s, "github %s" ]
      rawfile               : [ http://raw.githubusercontent.com/alissa-huskey/python-class/master/%s, "source %s" ]
      lesson                : [ http://github.com/alissa-huskey/python-class/blob/master/pythonclass/lessons/%s, "lesson %s" ]
    html_show_copyright     : false
    html_css_files          : [ "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" ]

    html_theme_options      :

      # spinx-book-theme config
      # https://sphinx-book-theme.readthedocs.io/en/latest/configure.html
      show_navbar_depth     : 3
      home_page_in_toc      : false

      repository_url        : *repo
      repository_branch     : *branch
      path_to_docs          : *path


      launch_buttons        :
        <<                  : *launch_buttons
      use_download_button   : false
      <<                    : *use_buttons

      # pydata-spyinx theme options
      # https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html
      navigation_with_keys  : false

